
["Damage Enchantments"]
	#Enchantment configuration for Damage Enchantments
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Efficiency]
	#Enchantment configuration for Efficiency
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Fire Aspect"]
	#Enchantment configuration for Fire Aspect
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Impaling]
	#Enchantment configuration for Impaling
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Knockback]
	#Enchantment configuration for Knockback
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Loot Bonus Enchantments"]
	#Enchantment configuration for Loot Bonus Enchantments
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Loyalty]
	#Enchantment configuration for Loyalty
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

[Lure]
	#Enchantment configuration for Lure
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

[Piercing]
	#Enchantment configuration for Piercing
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Power]
	#Enchantment configuration for Power
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Protection Enchantments"]
	#Enchantment configuration for Protection Enchantments
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Punch]
	#Enchantment configuration for Punch
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Quick Charge"]
	#Enchantment configuration for Quick Charge
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

[Respiration]
	#Enchantment configuration for Respiration
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

[Riptide]
	#Enchantment configuration for Riptide
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Soul Speed"]
	#Enchantment configuration for Soul Speed
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Sweeping Edge"]
	#Enchantment configuration for Sweeping Edge
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Thorns]
	#Enchantment configuration for Thorns
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Unbreaking]
	#Enchantment configuration for Unbreaking
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Enchanter Villager"]
	# Whether the enchanter villager is enabled
	isEnabled = true

["Attack Reach"]
	#Enchantment configuration for Attack Reach
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 3

["Block Reach"]
	#Enchantment configuration for Block Reach
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 3

["Cat Vision"]
	#Enchantment configuration for Cat Vision
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Camouflage]
	#Enchantment configuration for Camouflage
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Critical]
	#Enchantment configuration for Critical
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Cavernous Storage"]
	#Enchantment configuration for Cavernous Storage
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

["Double Break"]
	#Enchantment configuration for Double Break
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Fast Hopper"]
	#Enchantment configuration for Fast Hopper
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Flight]
	#Enchantment configuration for Flight
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3

[Freezing]
	#Enchantment configuration for Freezing
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 3

["Health Boost"]
	#Enchantment configuration for Health Boost
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

[Heavy]
	#Enchantment configuration for Heavy
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5

[Reinforcement]
	#Enchantment configuration for Reinforcement
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5

[Replanting]
	#Enchantment configuration for Replanting
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

["Step Assist"]
	#Enchantment configuration for Step Assist
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3

[Temper]
	#Enchantment configuration for Temper
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5

["Fast Smelt"]
	#Enchantment configuration for Fast Smelt
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1

["Fuel Efficient"]
	#Enchantment configuration for Fuel Efficient
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1

["Extra Experience"]
	#Enchantment configuration for Extra Experience
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1

["Heavy Blade"]
	#Enchantment configuration for Heavy Blade
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Light Blade"]
	#Enchantment configuration for Light Blade
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

[Blindness]
	#Enchantment configuration for Blindness
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

["Fire Resistance"]
	#Enchantment configuration for Fire Resistance
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Haste]
	#Enchantment configuration for Haste
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

[Hunger]
	#Enchantment configuration for Hunger
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

[Invisibility]
	#Enchantment configuration for Invisibility
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

["Jump Boost"]
	#Enchantment configuration for Jump Boost
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

["Mining Fatigue"]
	#Enchantment configuration for Mining Fatigue
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

[Nausea]
	#Enchantment configuration for Nausea
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Poison]
	#Enchantment configuration for Poison
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

[Regeneration]
	#Enchantment configuration for Regeneration
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

[Resistance]
	#Enchantment configuration for Resistance
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 4
	maxLevel = 3

[Saturation]
	#Enchantment configuration for Saturation
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

["Slow Falling"]
	#Enchantment configuration for Slow Falling
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Slowness]
	#Enchantment configuration for Slowness
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3

[Speed]
	#Enchantment configuration for Speed
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

[Strength]
	#Enchantment configuration for Strength
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

["Water Breathing"]
	#Enchantment configuration for Water Breathing
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Weakness]
	#Enchantment configuration for Weakness
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3

